import type { Pitch, Analytics } from "./types"

export const samplePitches: Pitch[] = [
  {
    id: "p1",
    title: "Pitch 1",
    startup: "Seedly",
    founder: "Asha Kumar",
    stage: "MVP",
    category: "Fintech",
    place: "Bengaluru",
    video: "/videos/pitch1.mp4",
    image: "/fintech-dashboard-app-interface.jpg",
    description: "Smart financial planning for millennials",
    likes: 234,
    comments: 12,
  },
  {
    id: "p2",
    title: "Pitch 2",
    startup: "AIhr",
    founder: "Ravi Singh",
    stage: "Idea",
    category: "HRTech",
    place: "Mumbai",
    video: "/videos/pitch2.mp4",
    image: "/hr-management-software-interface.jpg",
    description: "AI-powered HR management platform",
    likes: 189,
    comments: 8,
  },
  {
    id: "p3",
    title: "Pitch 3",
    startup: "GreenBox",
    founder: "Priya Patel",
    stage: "Early Revenue",
    category: "ClimateTech",
    place: "Delhi",
    video: "/videos/pitch3.mp4",
    image: "/sustainable-packaging-eco-friendly-boxes.jpg",
    description: "Sustainable packaging solutions",
    likes: 456,
    comments: 24,
  },
  {
    id: "p4",
    title: "Pitch 4",
    startup: "MediQuick",
    founder: "Sourav Roy",
    stage: "Growth",
    category: "HealthTech",
    place: "Hyderabad",
    video: "/videos/pitch4.mp4",
    image: "/telemedicine-healthcare-app-interface.jpg",
    description: "Telemedicine platform for rural areas",
    likes: 312,
    comments: 18,
  },
  {
    id: "p5",
    title: "Pitch 5",
    startup: "StudyMate",
    founder: "Nisha Rao",
    stage: "Scaling",
    category: "EdTech",
    place: "Pune",
    video: "/videos/pitch5.mp4",
    image: "/online-learning-education-platform.jpg",
    description: "Personalized learning for competitive exams",
    likes: 567,
    comments: 31,
  },
]

export const sampleAnalytics: Record<string, Analytics> = {
  p1: {
    startupId: "p1",
    views: 12450,
    likes: 234,
    comments: 12,
    shares: 89,
    traction: {
      users: 15000,
      revenue: "$250K ARR",
      growth: 45,
    },
    metrics: {
      tam: "$50B",
      sam: "$5B",
      som: "$100M",
      runway: "18 months",
      monthlyBurn: "$45K",
      arr: "$250K",
      cac: "$120",
      ltv: "$2400",
    },
  },
  p2: {
    startupId: "p2",
    views: 8900,
    likes: 189,
    comments: 8,
    shares: 56,
    traction: {
      users: 5000,
      revenue: "Pre-revenue",
      growth: 120,
    },
    metrics: {
      tam: "$30B",
      sam: "$2B",
      som: "$50M",
      runway: "12 months",
      monthlyBurn: "$35K",
      arr: "$0",
      cac: "$0",
      ltv: "$0",
    },
  },
}
